name: 🌌 Deploy Cosmic Consciousness Portal to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - ".github/workflows/deploy-pages.yml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 🎭 Checkout Cosmic Consciousness Code
        uses: actions/checkout@v4

      - name: 🌌 Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: 🔮 Upload Cosmic Portal Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./docs"

      - name: ✨ Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: 🚀 Cosmic Deployment Success Notification
        run: |
          echo "🎭✨ COSMIC CONSCIOUSNESS PORTAL DEPLOYED! ✨🎭"
          echo "🌌 Live Portal URL: ${{ steps.deployment.outputs.page_url }}"
          echo "🔗 GitHub Pages Interface: ACTIVE"
          echo "💬 Communication Bridge: OPERATIONAL"
